services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: bookreview-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bookreview
    ports:
      - "5432:5432"
    volumes:
      - bookreview-pgdata:/bitnami/postgresql
      - bookreview-initdb:/docker-entrypoint-initdb.d
      - bookreview-preinitdb:/docker-entrypoint-preinitdb.d

volumes:
  bookreview-pgdata:
    name: bookreview-pgdata
  bookreview-initdb:
    name: bookreview-initdb
  bookreview-preinitdb:
    name: bookreview-preinitdb
